{"frames":[{"func":"autoplot(lm5)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"autoplot.default(lm5)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"abort(glue(\"Objects of type \", glue_collapse(class(object), \"/\"), \n    \" not supported by autoplot.\"))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"signal_abort(cnd)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(fallback)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: Objects of type lm not supported by autoplot.\n\u001B[90mRun `rlang::last_error()` to see where the error occurred.\u001B[39m\n"}